export const hoursOfDay = [
  "01:00 AM",
  "02:00 AM",
  "03:00 AM",
  "04:00 AM",
  "05:00 AM",
  "06:00 AM",
  "07:00 AM",
  "08:00 AM",
  "09:00 AM",
  "10:00 AM",
  "11:00 AM",
  "12:00 PM",
  "01:00 PM",
  "02:00 PM",
  "03:00 PM",
  "04:00 PM",
  "05:00 PM",
  "06:00 PM",
  "07:00 PM",
  "08:00 PM",
  "09:00 PM",
  "10:00 PM",
  "11:00 PM",
  "12:00 AM",
];

export const internationalairlines = [
  { name: "Aeroméxico" },
  { name: "Air Canada" },
  { name: "Air Europa" },
  { name: "Air France" },
  { name: "Amaszonas Uruguay" },
  { name: "American Airlines" },
  { name: "Azul Linhas Aéreas" },
  { name: "Avianca" },
  { name: "Boliviana de Aviación" },
  { name: "British Airways" },
  { name: "Copa Airlines" },
  { name: "Cubana" },
  { name: "Delta Airlines" },
  { name: "Ethiopian Airlines" },
  { name: "Gol" },
  { name: "Iberia" },
  { name: "KLM" },
  { name: "Level" },
  { name: "Lufthansa" },
  { name: "Paranair" },
  { name: "Qatar" },
  { name: "Sky Airline" },
  { name: "Turkish Airlines" },
  { name: "United Airlines" },
  { name: "Other" },
];

export const nationalAirlines = [
  { name: "Aerolíneas Argentinas" },
  { name: "Lade" },
  { name: "Flybondi" },
  { name: "Jet Smart" },
  { name: "Other" },
];

export const airports = [
  { name: "Aeropuerto Internacional Ezeiza" },
  { name: "Aeroparque Internacional Jorge Newbery" },
];
